create database ecom;
use ecom;


CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    city VARCHAR(100)
);

CREATE TABLE products(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    price DECIMAL(10,2),
    stock INT
);

CREATE TABLE orders(
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    order_date DATE NOT NULL,
    total_amount DECIMAL(10,2),
    status VARCHAR(30),
    PRIMARY KEY(id, order_date)
    -- FOREIGN KEY(user_id)
    --     REFERENCES users(id)

)

PARTITION BY RANGE (YEAR(order_date))(
PARTITION p2024 VALUES LESS THAN (2025),
PARTITION p2025 VALUES LESS THAN (2026),
PARTITION p2026 VALUES LESS THAN (2027),
PARTITION pFuture VALUES LESS THAN MAXVALUE
);



ALTER TABLE orders
REORGANIZE PARTITION pFuture INTO (

    PARTITION p2028_Q1 VALUES LESS THAN ('2028-04-01'),

    PARTITION p2028_Q2 VALUES LESS THAN ('2028-07-01'),

    PARTITION p2028_Q3 VALUES LESS THAN ('2028-10-01'),

    PARTITION p2028_Q4 VALUES LESS THAN ('2029-01-01'),

    PARTITION pFuture VALUES LESS THAN (MAXVALUE)

);